name: oauth_link
description: A new flutter plugin project.
version: 1.0.0
homepage: https://github.com/rbcprolabs/oauth_link

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.scer.oauth_link
        pluginClass: OauthLinkPlugin
      ios:
        pluginClass: OauthLinkPlugin